### ISSUE TITLE
Size of navbar and managing color layer from background image?

### ISSUE THREAD

**Issue by akhilesh-k** [RyanFitzgerald/devportfolio-template#19]
How to change the size of navbar to the width of screen. How to removing blue layer from background image?

**Comment by RyanFitzgerald** [comment]
If you want the navbar to span the full width, add `width: 100%` to `header ul` as follows (around line 154 of styles.scss):

```SCSS
header {
   // ... Some styles

  ul {
        display: inline-block;
        background: $background;
        text-align: center;
        padding: 10px;
        margin: 0;
        width: 100% // Added
        border-bottom-right-radius: 4px;
        border-bottom-left-radius: 4px;
    }

    // Some more styles
}
```

If you want to remove the blue, delete the `<div id="lead-overlay"></div>` from your index.html

Hope that helps!
